spring:
  jpa:
    generate-ddl: true

    hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true

  datasource:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
